name = "luterraBot"
type = "javascript"
# wranglers does not support webpack 5
# type = "webpack" 
# webpack_config = "webpack.config.js"

route = ''
zone_id = ''
workers_dev = true
# usage_model = ''
compatibility_date = "2021-09-14"
# compatibility_flags = []

[build]
command = "npm run build"
# command = "npm install && npm run build"
[build.upload]
format = "service-worker"
